routes/admin.php
<?php

Route::group(['namespace' =>'Admin', 'as' => 'admin.'], function (){

    Route::namespace('Auth')->group(function (){
        Route::get('login' , 'LoginController@showLoginForm')->name('login');
        Route::post('login' , 'LoginController@login');
        Route::post('logout' , 'LoginController@login')->name('logout');
    });

    Route::group(['middleware' =>'admin'], function (){
        Route::get('dashboard', function (){
            return view('admin.dashboard');
        })->name('dashboard');

        $resourceMethods = ['except' => ['show']];
        Route::resource('user', 'UserController', $resourceMethods);
        Route::resource('coach', 'CoachController', $resourceMethods);
        Route::resource('mountain', 'MountainBaseController',  $resourceMethods);
        Route::resource('page', 'StaticPageController',  $resourceMethods);
        Route::resource('review', 'ReviewController',  $resourceMethods);

        Route::group(['as'=>'settings.'],function (){
            Route::get('/settings','SettingsController@edit')->name('edit');
            Route::post('/settings','SettingsController@edit')->name('update');
        });
    });
});

Route::fallback(function (){return redirect()->route('admin.login');});

routes/web.php
<?php


Route::get('/','MainController@home')->name('home');;

Auth::routes();

Route::resources([
    'reserve' => 'ReservationController',
    'coach' => 'CoachController',
    'mountain'=>'MountainBaseController',
]);

//Route::resource('review', 'ReviewController')->only(['store']);
Route::post('review/{model}/store','ReviewController@store')->name('review.store');

Route::get('find' , 'MainController@finder')->name('finder');
Route::get('/home', 'HomeController@index' )->name('home');
Route::get('/profile', 'ProfileController@index' )->name('profile');

Route::prefix('admin')->group(base_path('routes/admin.php'));

Route::group(['middleware' => 'static'], function() {
    Route::get('/{slug}', 'PageController@show');
});

app/Models/Coach/Coach.php
<?php

namespace App\Models\Coach;

use App\Services\DomainCheckService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Session;

class Coach extends Model
{

    protected $appends = ['rating' , 'full_name'];

    protected $dates = ['birthdate'];

    protected $fillable = [
        'firstname', 'lastname','experience','description','image','price','birthdate'
    ];

    public function reviews(){

        return $this->morphMany('App\Models\Review', 'reviewable' , 'reviewable_type');
    }

    public function reviewsActive(){

        return $this->reviews()->active();
    }

    public function getRatingAttribute(){

        return $this->reviewsActive->avg('rating');
    }

    public function reservations(){
        return $this->hasMany('App\Models\Reservation\Reservation');
    }

    public function getFullNameAttribute(){
        return "{$this->firstname} {$this->lastname}";
    }

    public function getBirthdayAttribute(){
        return $this->birthdate->format('j F Y');
    }

    public function getBirthdateValueAttribute(){
        return $this->birthdate->toDateString();
    }

    public function getExperienceStringAttribute(){
        $num = $this->attributes['experience'];
        $word = unit_case($num);

        return "{$num} {$word}";
    }

    public function getPriceCurrencyAttribute(){
        $currency = config('client_site.currency');

        return "{$this->price} {$currency}";
    }
    //Кажется не юзается
    public function getImagePath(){
        $path = "app/public/{$this->image}";
        return storage_path($path);
    }

    public function getImageAttribute($value){
        return asset($value ? "storage/{$value}"  : 'images/no-image.png');
    }
}

app/Models/Coach/Rating.php
<?php

namespace App\Models\Coach;

use Illuminate\Database\Eloquent\Model;

class Rating extends Model
{
    protected $table = 'coach_ratings';



}

app/Http/Controllers/Admin/CoachController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Services\CoachService;
use App\Repositories\CoachRepository;
use App\Http\Requests\Coach as CoachRequest;
use App\Http\Controllers\Controller;

class CoachController extends Controller
{
    protected $coach;

    protected $service;


    public function __construct(CoachRepository $coach , CoachService $service){
        $this->coach = $coach;
        $this->service = $service;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(){
        $coaches = $this->coach->paginateWith(15,'reviews');

        return view('admin.sections.coaches.index' , compact('coaches'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id){
        $coach = $this->coach->find($id);
        return view('admin.sections.coaches.show' , compact('coach'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(){
        return view('admin.sections.coaches.create');
    }

    /**
     * @param CoachRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CoachRequest $request){
        $coach = $this->coach->create($request->except('image'));

        if($request->hasFile('image')){
            $coach->image = $this->service->handleUploadImage($request->file('image'));
            $coach->save();
        }

        return redirect()->route('admin.coach.index')->with('message', 'Тренер создан');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id){
        $coach = $this->coach->find($id);

        return view('admin.sections.coaches.edit' , compact('coach'));
    }

    /**
     * @param CoachRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(CoachRequest $request, $id){
        $coach = $this->coach->update($request->except('image'), $id);

        if ($request->hasFile('image')){
            $coach->image = $this->service->handleUpdateImage($request->file('image'), $coach->image);
            $coach->save();
        }

        return redirect()->route('admin.coach.index')->with('message', 'Тренер обновлен');
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id){
        $this->coach->delete($id);

        return redirect()->route('admin.coach.index')->with('message', 'Тренер удален');
    }

}

app/Http/Controllers/CoachController.php
<?php

namespace App\Http\Controllers;

use App\Models\Review;
use SEO;
use App\Http\Controllers\Controller;
use App\Repositories\CoachRepository;

class CoachController extends Controller
{
    protected $coach;

    public function __construct(CoachRepository $coach){

        $this->coach = $coach;
    }

    public function index(){
        SEO::setTitle('Тренера');
        $coaches = $this->coach->paginate(4);
        return view('pages.coaches.index', compact('coaches'));
    }

    public function show($id){
        $coach = $this->coach->findWith($id, ['reservations', 'reviews' => function ($query) { $query->active(); }, 'reviews.user']);


        if (auth()->check()){
            $canReview = Review::where('user_id' , auth()->user()->id)->exists();
        }

        SEO::setTitle($coach->full_name);
        SEO::setDescription($coach->description);
        SEO::opengraph()->addImage($coach->image);

        return view('pages.coaches.show', compact('coach' , 'canReview'));
    }
}

resources/views/admin/sections/coaches/create.blade.php
@extends('layouts.admin')


@section('content')
    <div class="row">
        <div class="col-md-9">
            <form action="{{route('admin.coach.store')}}" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                {{csrf_field('delete')}}
                <div class="card card-accent-secondary">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i>
                        Добавить тренера
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Имя</label>
                                <div class="col-md-9">
                                    <input type="text" id="text-input" name="firstname" class="form-control" placeholder="Имя">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Фамилия</label>
                                <div class="col-md-9">
                                    <input type="text" id="text-input" name="lastname" class="form-control" placeholder="Фамилия">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Кол-во лет опыта</label>
                                <div class="col-md-9">
                                    <input type="number" id="text-input" name="experience" class="form-control" placeholder="Кол-во лет опыта">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Описание</label>
                                <div class="col-md-9">
                                    <input type="textarea-input" rows="4" id="textarea-input" name="description" class="form-control" placeholder="Описание">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Стоимость часового занятия</label>
                                <div class="col-md-9">
                                    <input type="number" id="text-input" name="price" class="form-control" placeholder="Стоимость часового занятия">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Дата рождения</label>
                                <div class="col-md-9">
                                    <input type="date" id="date-input" name="birthdate" class="form-control" placeholder="Дата рождения">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="image-input">Фотография</label>
                                <div class="col-md-9">
                                    <input type="file" id="image-input" name="image" class="form-control" placeholder="Фотография">
                                </div>
                            </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>Сохранить</button>
                        <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i>Сбросить</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sections/coaches/edit.blade.php
@extends('layouts.admin')


@section('content')
    <div class="row">
        <div class="col-md-9">
            <form action="{{route('admin.coach.update',$coach->id)}}" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                {{method_field('PUT')}}
                <div class="card card-accent-secondary">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i>
                        Изменить тренера
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="text-input">Имя</label>
                                    <div class="col-md-9">
                                        <input type="text" id="text-input" name="firstname" class="form-control" placeholder="Имя" value="{{$coach->firstname}}">
                                    </div>
                                </div>
                        <div class="form-group row">
                            <label class="col-md-3 form-control-label" for="text-input">Фамилия</label>
                            <div class="col-md-9">
                                <input type="text" id="text-input" name="lastname" class="form-control" placeholder="Фамилия" value="{{$coach->lastname}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 form-control-label" for="text-input">Кол-во лет опыта</label>
                            <div class="col-md-9">
                                <input type="number" step="0.5" min="0"  id="text-input" name="experience" class="form-control" placeholder="Кол-во лет опыта" value="{{$coach->experience}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 form-control-label" for="text-input">Описание</label>
                            <div class="col-md-9">
                                <input type="textarea-input" rows="4" id="textarea-input" name="description" class="form-control" placeholder="Описание" value="{{$coach->description}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 form-control-label" for="text-input">Стоимость часового занятия</label>
                            <div class="col-md-9">
                                <input type="number" id="text-input" name="price" class="form-control" placeholder="Стоимость часового занятия" value="{{$coach->price}}">
                            </div>
                        </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Дата рождения</label>
                                <div class="col-md-9">
                                    <input type="date" id="date-input" name="birthdate" class="form-control" placeholder="Дата рождения" value="{{$coach->birthdate_value}}">
                                </div>
                            </div>
                        <div class="form-group row">
                            <label class="col-md-3 form-control-label" for="image-input">Фотография</label>
                            <div class="col-md-9">
                                <div>
                                    <img src="{{$coach->image}}" class="img-responsive img-thumbnail" style="max-width: 200px">
                                </div>
                                <input type="file" id="image-input" name="image" class="form-control" placeholder="Фотография">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>Сохранить</button>
                        <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i>Сбросить</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sections/coaches/index.blade.php
@extends('layouts.admin')


@section('content')
    <div class="row">
        <div class="col-md-9">
          <div class="card card-accent-secondary">
              <div class="card-header">
                  <i class="fa fa-align-justify"></i>
                  Все тренера
              </div>
              <div class="card-body">
                  @if($msg = session('message'))
                      <div class="alert alert-success" role="alert">
                          {{ $msg }}
                      </div>
                  @endif
                  <table class="table table-striped">
                      <thead>
                      <tr>
                          <th>Имя</th>
                          <th>Фамилия</th>
                          <th>Рейтинг</th>
                          <th>Статус</th>
                          <th></th>
                      </tr>
                      </thead>
                      <tbody>
                      @foreach($coaches as $coach)
                          <tr>
                              <td>{{$coach->firstname}}</td>
                              <td>{{$coach->lastname}}</td>
                              <td>@include('components.rating',['value' => $coach->rating])</td>
                              <td><span class="badge badge-secondary">active</span></td>
                              <td><a href="{{route('admin.coach.edit', $coach->id)}}" class="btn btn-primary">Редактировать</a></td>
                          </tr>
                      @endforeach
                      </tbody>
                  </table>
                  {{ $coaches->links('vendor.pagination.bootstrap-4') }}
              </div>
          </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <a href="{{route('admin.coach.create')}}" class="btn btn-secondary">Добавить</a>
                </div>
            </div>
        </div>
    </div>
@endsection