routes/admin.php
<?php

Route::group(['namespace' =>'Admin', 'as' => 'admin.'], function (){

    Route::namespace('Auth')->group(function (){
        Route::get('login' , 'LoginController@showLoginForm')->name('login');
        Route::post('login' , 'LoginController@login');
        Route::post('logout' , 'LoginController@login')->name('logout');
    });

    Route::group(['middleware' =>'admin'], function (){
        Route::get('dashboard', function (){
            return view('admin.dashboard');
        })->name('dashboard');

        $resourceMethods = ['except' => ['show']];
        Route::resource('user', 'UserController', $resourceMethods);
        Route::resource('coach', 'CoachController', $resourceMethods);
        Route::resource('mountain', 'MountainBaseController',  $resourceMethods);
        Route::resource('page', 'StaticPageController',  $resourceMethods);
        Route::resource('review', 'ReviewController',  $resourceMethods);

        Route::group(['as'=>'settings.'],function (){
            Route::get('/settings','SettingsController@edit')->name('edit');
            Route::post('/settings','SettingsController@edit')->name('update');
        });
    });
});

Route::fallback(function (){return redirect()->route('admin.login');});

routes/web.php
<?php


Route::get('/','MainController@home')->name('home');;

Auth::routes();

Route::resources([
    'reserve' => 'ReservationController',
    'coach' => 'CoachController',
    'mountain'=>'MountainBaseController',
]);

//Route::resource('review', 'ReviewController')->only(['store']);
Route::post('review/{model}/store','ReviewController@store')->name('review.store');

Route::get('find' , 'MainController@finder')->name('finder');
Route::get('/home', 'HomeController@index' )->name('home');
Route::get('/profile', 'ProfileController@index' )->name('profile');

Route::prefix('admin')->group(base_path('routes/admin.php'));

Route::group(['middleware' => 'static'], function() {
    Route::get('/{slug}', 'PageController@show');
});

app/Models/Coach/Coach.php
<?php

namespace App\Models\Coach;

use App\Services\DomainCheckService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Session;

class Coach extends Model
{

    protected $appends = ['rating' , 'full_name'];

    protected $dates = ['birthdate'];

    protected $fillable = [
        'firstname', 'lastname','experience','description','image','price','birthdate'
    ];

    public function reviews(){

        return $this->morphMany('App\Models\Review', 'reviewable' , 'reviewable_type');
    }

    public function reviewsActive(){

        return $this->reviews()->active();
    }

    public function getRatingAttribute(){

        return $this->reviewsActive->avg('rating');
    }

    public function reservations(){
        return $this->hasMany('App\Models\Reservation\Reservation');
    }

    public function getFullNameAttribute(){
        return "{$this->firstname} {$this->lastname}";
    }

    public function getBirthdayAttribute(){
        return $this->birthdate->format('j F Y');
    }

    public function getBirthdateValueAttribute(){
        return $this->birthdate->toDateString();
    }

    public function getExperienceStringAttribute(){
        $num = $this->attributes['experience'];
        $word = unit_case($num);

        return "{$num} {$word}";
    }

    public function getPriceCurrencyAttribute(){
        $currency = config('client_site.currency');

        return "{$this->price} {$currency}";
    }
    //Кажется не юзается
    public function getImagePath(){
        $path = "app/public/{$this->image}";
        return storage_path($path);
    }

    public function getImageAttribute($value){
        return asset($value ? "storage/{$value}"  : 'images/no-image.png');
    }
}

resources/views/admin/sections/bases/create.blade.php
@extends('layouts.admin')


@section('content')
    <div class="row">
        <div class="col-md-9">
            <form action="{{route('admin.mountain.store')}}" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                {{csrf_field('delete')}}
                <div class="card card-accent-secondary">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i>
                        Добавить Горную базу
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Название</label>
                                <div class="col-md-9">
                                    <input type="text" id="text-input" name="name" class="form-control" placeholder="Название">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Цена в час</label>
                                <div class="col-md-9">
                                    <input type="text" id="text-input" name="price" class="form-control" placeholder="Кол-во лет опыта">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Описание</label>
                                <div class="col-md-9">
                                    <input type="textarea-input" rows="4" id="textarea-input" name="description" class="form-control" placeholder="Описание">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Адерс</label>
                                <div class="col-md-9">
                                    <input type="text" id="text-input" name="address" class="form-control" placeholder="Стоимость часового занятия">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Услуги</label>
                                <div class="col-md-9">
                                    <select name="features[]" class="form-control selectpicker" style="width: 100%" multiple>
                                        <option {{in_array('wifi' , old('features') ?? []) ? 'selected' : '' }} value="wifi">Wi-fi</option>
                                        <option {{in_array('utensils' , old('features') ?? []) ? 'selected' : ''}} value="utensils">Кухня</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="image-input">Фотография</label>
                                <div class="col-md-9">
                                    <input type="file" id="image-input" name="image" class="form-control" placeholder="Фотография">
                                </div>
                            </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>Сохранить</button>
                        <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i>Сбросить</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sections/bases/edit.blade.php
@extends('layouts.admin')


@section('content')
    <div class="row">
        <div class="col-md-9">
            <form action="{{route('admin.mountain.update',$mountain->id)}}" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                {{method_field('PUT')}}
                <div class="card card-accent-secondary">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i>
                        Изменить горную базу
                    </div>
                    <div class="card-body">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Название</label>
                                <div class="col-md-9">
                                    <input type="text" id="text-input" name="name" class="form-control" placeholder="Фамилия" value="{{$mountain->name}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Цена в час</label>
                                <div class="col-md-9">
                                    <input type="text" id="text-input" name="price" class="form-control" placeholder="Кол-во лет опыта" value="{{$mountain->price}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Описание</label>
                                <div class="col-md-9">
                                    <input type="textarea-input" rows="4" id="textarea-input" name="description" class="form-control" placeholder="Описание" value="{{$mountain->description}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Адрес</label>
                                <div class="col-md-9">
                                    <input type="text" id="text-input" name="address" class="form-control" placeholder="Стоимость часового занятия" value="{{$mountain->address}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Услуги</label>
                                <div class="col-md-9">
                                    <select name="features[]" class="form-control selectpicker" style="width: 100%" multiple>
                                        <option {{in_array('wifi' , $mountain->features) ? 'selected' : '' }} value="wifi">Wi-fi</option>
                                        <option {{in_array('utensils' , $mountain->features) ? 'selected' : ''}} value="utensils">Кухня</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                            <label class="col-md-3 form-control-label" for="image-input">Фотография</label>
                            <div class="col-md-9">
                                <div>
                                    <img src="{{$mountain->image}}" class="img-responsive img-thumbnail" style="max-width: 200px">
                                </div>
                                <input type="file" id="image-input" name="image" class="form-control" placeholder="Фотография">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>Сохранить</button>
                        <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i>Сбросить</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sections/bases/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="row">
        <div class="col-md-9">
            <div class="card card-accent-secondary">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i>
                    Горы
                </div>
                <div class="card-body">
                    @if($msg = session('message'))
                        <div class="alert alert-success" role="alert">
                            {{$msg}}
                        </div>
                    @endif
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Цена</th>
                            <th>Адрес</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($mountains as $mountain)
                            <tr>
                                <td>{{$mountain->name}}</td>
                                <td><span class="badge badge-primary">{{$mountain->price_currency }}</span></td>
                                <td>{{$mountain->address }}</td>
                                <td>
                                    <a href="{{route('admin.mountain.edit', $mountain->id)}}" class="btn btn-primary">
                                        Редактировать
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $mountains->links('vendor.pagination.bootstrap-4') }}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <a href="{{route('admin.mountain.create')}}" class="btn btn-secondary">Добавить</a>
                </div>
            </div>
        </div>
    </div>
@endsection