routes/admin.php
<?php

Route::group(['namespace' =>'Admin', 'as' => 'admin.'], function (){

    Route::namespace('Auth')->group(function (){
        Route::get('login' , 'LoginController@showLoginForm')->name('login');
        Route::post('login' , 'LoginController@login');
        Route::post('logout' , 'LoginController@login')->name('logout');
    });

    Route::group(['middleware' =>'admin'], function (){
        Route::get('dashboard', function (){
            return view('admin.dashboard');
        })->name('dashboard');

        $resourceMethods = ['except' => ['show']];
        Route::resource('user', 'UserController', $resourceMethods);
        Route::resource('coach', 'CoachController', $resourceMethods);
        Route::resource('mountain', 'MountainBaseController',  $resourceMethods);
        Route::resource('page', 'StaticPageController',  $resourceMethods);
        Route::resource('review', 'ReviewController',  $resourceMethods);

        Route::group(['as'=>'settings.'],function (){
            Route::get('/settings','SettingsController@edit')->name('edit');
            Route::post('/settings','SettingsController@edit')->name('update');
        });
    });
});

Route::fallback(function (){return redirect()->route('admin.login');});

routes/web.php
<?php


Route::get('/','MainController@home')->name('home');;

Auth::routes();

Route::resources([
    'reserve' => 'ReservationController',
    'coach' => 'CoachController',
    'mountain'=>'MountainBaseController',
]);

//Route::resource('review', 'ReviewController')->only(['store']);
Route::post('review/{model}/store','ReviewController@store')->name('review.store');

Route::get('find' , 'MainController@finder')->name('finder');
Route::get('/home', 'HomeController@index' )->name('home');
Route::get('/profile', 'ProfileController@index' )->name('profile');

Route::prefix('admin')->group(base_path('routes/admin.php'));

Route::group(['middleware' => 'static'], function() {
    Route::get('/{slug}', 'PageController@show');
});

app/Models/Page.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Page extends Model
{

    protected $fillable = ['title', 'slug' , 'content'];



    public function getSlugWithSlashAttribute(){
        return "/{$this->attributes['slug']}";
    }

}

resources/views/admin/sections/pages/create.blade.php
@extends('layouts.admin')


@section('content')
    <div class="row">
        <div class="col-md-9">
            <form action="{{route('admin.page.store')}}" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="card card-accent-secondary">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i>
                        Добавить страницу
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Заголовок</label>
                                <div class="col-md-9">
                                    <input type="text" id="text-input" name="title" class="form-control" placeholder="Заголовок" {{ old('title') }}>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Путь</label>
                                <div class="col-md-9">
                                    <input type="text" id="text-input" name="slug" class="form-control" placeholder="Путь" value="{{ old('slug') }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 form-control-label" for="text-input">Путь</label>
                                <div class="col-md-9">
                                    <textarea id="summernote" name="content" >{{ old('content') }}</textarea>
                                </div>
                            </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>Сохранить</button>
                        <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i>Сбросить</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sections/pages/edit.blade.php
@extends('layouts.admin')


@section('content')
    <div class="row">
        <div class="col-md-9">
            <form action="{{route('admin.page.update',$page->id)}}" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                {{method_field('PUT')}}
                <div class="card card-accent-secondary">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i>
                       Изменить страницу
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="form-group row">
                            <label class="col-md-3 form-control-label" for="text-input">Заголовок</label>
                            <div class="col-md-9">
                                <input type="text" id="text-input" name="title" class="form-control" placeholder="Заголовок" value="{{$page->title}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 form-control-label" for="text-input">Путь</label>
                            <div class="col-md-9">
                                <input type="text" id="text-input" name="slug" class="form-control" placeholder="Путь" value="{{$page->slug}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 form-control-label" for="text-input">Контент</label>
                            <div class="col-md-9">
                                <textarea id="summernote" name="content" >{{$page->content}}</textarea>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>Сохранить</button>
                        <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i>Сбросить</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('admin.page.destroy', $page->id)}}" method="POST">
                        {{method_field('DELETE')}}
                        {{csrf_field()}}
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sections/pages/index.blade.php
@extends('layouts.admin')


@section('content')
    <div class="row">
        <div class="col-md-9">
            <div class="card card-accent-secondary">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i>
                    Статические страницы
                </div>
                <div class="card-body">
                    @if($msg = session('message'))
                        <div class="alert alert-success" role="alert">
                            {{ $msg }}
                        </div>
                    @endif
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Заголовок</th>
                            <th>Адрес</th>
                            <th>Статус</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($pages as $page)
                            <tr>
                                <td>{{$page->title}}</td>
                                <td>{{$page->slug_with_slash}}</td>
                                <td><span class="badge badge-secondary">active</span></td>
                                <td><a href="{{route('admin.page.edit', $page->id)}}" class="btn btn-primary">Редактировать</a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $pages->links('vendor.pagination.bootstrap-4') }}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <a href="{{route('admin.page.create')}}" class="btn btn-secondary">Добавить</a>
                </div>
            </div>
        </div>
    </div>
@endsection