routes/admin.php
<?php

Route::group(['namespace' =>'Admin', 'as' => 'admin.'], function (){

    Route::namespace('Auth')->group(function (){
        Route::get('login' , 'LoginController@showLoginForm')->name('login');
        Route::post('login' , 'LoginController@login');
        Route::post('logout' , 'LoginController@login')->name('logout');
    });

    Route::group(['middleware' =>'admin'], function (){
        Route::get('dashboard', function (){
            return view('admin.dashboard');
        })->name('dashboard');

        $resourceMethods = ['except' => ['show']];
        Route::resource('user', 'UserController', $resourceMethods);
        Route::resource('coach', 'CoachController', $resourceMethods);
        Route::resource('mountain', 'MountainBaseController',  $resourceMethods);
        Route::resource('page', 'StaticPageController',  $resourceMethods);
        Route::resource('review', 'ReviewController',  $resourceMethods);

        Route::group(['as'=>'settings.'],function (){
            Route::get('/settings','SettingsController@edit')->name('edit');
            Route::post('/settings','SettingsController@edit')->name('update');
        });
    });
});

Route::fallback(function (){return redirect()->route('admin.login');});

routes/web.php
<?php


Route::get('/','MainController@home')->name('home');;

Auth::routes();

Route::resources([
    'reserve' => 'ReservationController',
    'coach' => 'CoachController',
    'mountain'=>'MountainBaseController',
]);

//Route::resource('review', 'ReviewController')->only(['store']);
Route::post('review/{model}/store','ReviewController@store')->name('review.store');

Route::get('find' , 'MainController@finder')->name('finder');
Route::get('/home', 'HomeController@index' )->name('home');
Route::get('/profile', 'ProfileController@index' )->name('profile');

Route::prefix('admin')->group(base_path('routes/admin.php'));

Route::group(['middleware' => 'static'], function() {
    Route::get('/{slug}', 'PageController@show');
});

app/Models/Coach/Coach.php
<?php

namespace App\Models\Coach;

use App\Services\DomainCheckService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Session;

class Coach extends Model
{

    protected $appends = ['rating' , 'full_name'];

    protected $dates = ['birthdate'];

    protected $fillable = [
        'firstname', 'lastname','experience','description','image','price','birthdate'
    ];

    public function reviews(){

        return $this->morphMany('App\Models\Review', 'reviewable' , 'reviewable_type');
    }

    public function reviewsActive(){

        return $this->reviews()->active();
    }

    public function getRatingAttribute(){

        return $this->reviewsActive->avg('rating');
    }

    public function reservations(){
        return $this->hasMany('App\Models\Reservation\Reservation');
    }

    public function getFullNameAttribute(){
        return "{$this->firstname} {$this->lastname}";
    }

    public function getBirthdayAttribute(){
        return $this->birthdate->format('j F Y');
    }

    public function getBirthdateValueAttribute(){
        return $this->birthdate->toDateString();
    }

    public function getExperienceStringAttribute(){
        $num = $this->attributes['experience'];
        $word = unit_case($num);

        return "{$num} {$word}";
    }

    public function getPriceCurrencyAttribute(){
        $currency = config('client_site.currency');

        return "{$this->price} {$currency}";
    }
    //Кажется не юзается
    public function getImagePath(){
        $path = "app/public/{$this->image}";
        return storage_path($path);
    }

    public function getImageAttribute($value){
        return asset($value ? "storage/{$value}"  : 'images/no-image.png');
    }
}

resources/views/pages/coach.blade.php
@extends('layouts.app')

@section('breadcrumbs', Breadcrumbs::render('coach', $coach))

@section('content')
    <div class="container mx-auto">
        <h1>{{$coach->full_name}}</h1>
        <div> @include('components.rating',['value' => $coach->rating])</div>
        <div class="card shadow mx-2">
            <div class="flex mb-4 mt-6">
                <div class="cover-image" style="background-image: url('{{ asset("storage/{$coach->image}")}}')">
                </div>
                <div class="w-2/3 bg-grey-lightest p-8" >

                    <div class="py-8">
                        <a href="https://vk.com/rentmountain" class="ml-4 min-w-full text-center bg-blue-light rounded-full w-24 h-24 p-2 hover:bg-blue">
                            <i class="fab fa-vk"></i>
                        </a>
                        <a href="https://www.youtube.com/rentmountein" class="ml-4 min-w-full text-center bg-red-light rounded-full w-24 h-24 p-2 hover:bg-red">
                            <i class="fab fa-youtube"></i>
                        </a>
                        <a href="https://www.facebook.com/rentmountein" class="ml-4 min-w-full text-center bg-blue-dark rounded-full w-24 h-24 py-2 px-4 hover:bg-red">
                            <i class="fab fa-facebook"></i>
                        </a>
                    </div>

                    <h3 class="mb-4">О инструкторе</h3>
                    {{$coach->description}}
                    <h3 class="my-4">Цена</h3>
                    {{$coach->price_currency}} в час
                    <hr>
                    <div class="mt-6">
                        <a class="btn btn-blue " href="{{route('reserve.index')}}">Забронировать</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="block">
            <div class="card shadow w-1/2 float-left">
                <div class="w-full p-4">
                    <h3 class="">Отзывы</h3>
                </div>
                <div class="flex flex-col">
                @forelse($coach->reviews as $review)
                        <div class="w-full bg-white border-t border-b">
                                <div class="bg-grey-lightest p-4 pl-8 flex border-t border-grey-lighter">
                                    <div class="w-12 mr-2 flex-no-shrink">
                                        <img class="p-2 rounded rounded-full" src="https://scontent-frt3-1.cdninstagram.com/t51.2885-19/s150x150/22638783_1031626323645160_6412994168498421760_n.jpg">
                                    </div>
                                    <div class="p-2 flex-grow">
                                        <header>
                                            <a href="#" class="text-black no-underline">
                                                <span class="font-medium">{{$review->user->name}}</span>
                                            </a>
                                            <div class="text-xs text-grey flex items-center my-1">
                                                <i class="far fa-calendar-alt"></i>
                                                <span class="ml-2">{{$review->created_at}}</span>
                                            </div>
                                        </header>
                                        <article class="py-4 text-grey-darkest leading-normal">
                                            {{$review->text}}
                                        </article>
                                        <footer class="border-t border-grey-lighter text-sm flex">

                                        </footer>
                                    </div>
                                </div>
                            </div>
                @empty
                    <div class="p-4">
                        Отзывов еще нет.
                    </div>
                @endforelse
                </div>
            </div>
            <div class="card w-1/2 float-left p-4">
                @auth
                <div class="w-full p-8">
                    <h3 class="">Написать отзыв</h3>
                </div>
                    @if($msg = session('message'))
                    <div class="w-full p-8 bg-green">
                        <h3 class="">{{ $msg }}</h3>
                    </div>
                    @endif
                    @if($canReview)
                        <form action="{{route('review.store')}}" method="post" class="p-4">
                            {{csrf_field()}}
                            <input type="hidden" name="review_type" value="coach">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <input type="hidden" value="{{$coach->id}}" name="id">
                            <div class="form-field">
                                <div class="w-full">
                                    <label class="form-field__label" for="inline-full-name">
                                        Отзыв:
                                    </label>
                                    <textarea name="text" rows="10" class="form-field__text"></textarea>
                                </div>
                            </div>
                            <div class="form-field">
                                <div class="md:w-1/3">
                                    <label class="form-field__label" for="inline-full-name">
                                        Оценка
                                    </label>
                                </div>
                                <div class="md:w-2/3">
                                    <div id="select-rating"></div>
                                </div>
                            </div>
                            <div class="form-field">
                                <button class="btn btn-blue" type="submit">Отправить</button>
                            </div>
                        </form>
                    @else
                        <div class="p-4">
                            Вы уже оставляли отзыв
                        </div>
                    @endif
                @else
                    <div class="p-6">
                        Зарегистрийтесь или войдите чтобы оставить отзыв
                    </div>
                @endauth
            </div>
        </div>


    </div>
@endsection

resources/views/pages/home.blade.php
@extends('layouts.app')
@section('content')
    <div class="container mx-auto">
        <div class="profile">
            <h1 class="title">Новости</h1>
            блок новостей
            <h1 class="title">Популярные тренера</h1>
            блок тренеров
            <h1 class="title">Экипировка</h1>
            блок экипировки
        </div>
    </div>
@endsection

resources/views/pages/main.blade.php
@extends('layouts.main')

@section('content')

        <!-- Main banner -->
        <div id="main-banner">
            <div class="container1">
                <div class="logo">
                    <img src="images/logo.png">
                    <span>
              <h1>COMPANY LOGO</h1>
              <div>АГРЕГАТОР ВАШЕГО ОТДЫХА</div>
            </span>
                </div>
                <div class="consult-phone">
                    <div><i class="fas fa-phone-volume"></i>   Нужна консультация?</div>
                    <h1>+7 920 625 28-14</h1>
                </div>
                <!-- Search block -->
                <div class="search-block-container">
                    <form action="{{route('finder')}}" class="search-block">
                        <div class="sblock">
                            <i class="fas fa-map-marker-alt"></i>
                            <div class="city-block">
                                <select name="city" class="city">
                                    <option>Владимир</option>
                                    <option>Омск</option>
                                    <option>Орёл</option>
                                </select>
                            </div>
                            <i class="fas fa-angle-down"></i>
                        </div>
                        <div class="sblock">
                            <input type="text" name="date" class="tcal date" placeholder="с 21.03.2018">
                        </div>
                        <div class="sblock">
                            <i class="far fa-moon"></i>
                            <input type="text" name="nigths" class="" placeholder="на 7 ночей">
                        </div>
                        <div class="sblock">
                            <i class="far fa-user"></i>
                            <input type="text" name="adults" class=""  placeholder="2 взрослых">
                        </div>
                        <div class="sblock">
                            <button class="search-btn">
                                <i class="fas fa-search"></i>
                                НАЙТИ БАЗУ
                            </button>
                        </div>
                    </form>
                </div>
                <!-- /Search block -->
            </div>
        </div>
        <!-- /Main banner -->
        <!-- Service block -->
        <div class="service-block">
            <div class="serv-block">
                <div class="serv-block-txt">
                    <img src="images/serv-block-1-img.png">
                    <span>
              Арендовать базу<br>
              отдыха
            </span>
                </div>
            </div>
            <div class="serv-block">
                <div class="serv-block-txt">
                    <img src="images/serv-block-2-img.png">
                    <span>
              Велосипедные<br>
              прогулки
            </span>
                </div>
            </div>
            <div class="serv-block">

                <div class="serv-block-txt">
                    <img src="images/serv-block-3-img.png">
                    <span>
              Сноуборд и<br>
              лыжный спорт
            </span>
                </div>

            </div>
            <div class="serv-block">

                <div class="serv-block-txt">
                    <img src="images/serv-block-4-img.png">
                    <span>
              Активный отдых<br>
              на природе
            </span>
                </div>
            </div>
            <div class="serv-block">
                <div class="serv-block-txt">
                    <img src="images/serv-block-5-img.png">
                    <span>
              Аренда<br>
              экипировки
            </span>
                </div>
            </div>
        </div>
        <!-- /Service block -->

        <!-- Bazy block -->
        <div class="bazy-block">
            <h1>Популярные базы отдыха</h1>
            <div class="container2">

                <div class="bz-blocks row">
                    @foreach($hotels as $hostel)
                        <div class="col-md-6 my-4">
                            <div class="bz-block m-2">
                                <div class="bz-b1">
                                    <img class="bz-b1-image" src="{{$hostel->image}}">
                                    <div class="features">
                                        @foreach($hostel->features as $feature)
                                            <i class="fas fa-{{$feature}}"></i>
                                        @endforeach
                                    </div>
                                </div>
                                <div class="bz-b2">
                                    <div>
                                        <a class="base-title" href="{{route('mountain.show' , $hostel)}}">{{$hostel->name}}</a>
                                    </div>
                                    <div class="marks">
                                        @include('components.rating',['value' => $hostel->rating ?? 5])
                                        <span>Оценка: {{$hostel->rating ?? 0 }} из 5 (<a href="#">{{ $hostel->reviewsActive->count() }} отзывов</a>)</span>
                                    </div>
                                    <div class="txt">
                                        {{$hostel->description}}
                                    </div>
                                    <div class="options">
                                        <button class="red-btn">от {{$hostel->price}} ₽</button>
                                        <span class="izbrannoe">
                                            <i class="far fa-heart"></i>
                                            В избранное
                                        </span>
                                        <a href="{{route('mountain.show' , $hostel) . '#map' }}" class="gps">
                                            <i class="fas fa-map-marker-alt"></i>
                                            На карте
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
                <a href="{{route('mountain.index')}}" class="more-btn">БОЛЬШЕ ПРЕДЛОЖЕНИЙ</a>
            </div>
        </div>
        <!-- /Bazy block -->


        <!-- Instruktory block -->
        <div class="instruktory-block">
            <img src="images/bike.png" class="bike">
            <div class="row container2">
                <div class="offset-xl-6 offset-lg-6 offset-md-2 col-xl-5 col-lg-4 col-md-10">
                    <div class="txt">
                        <span>
                            <img src="images/checked-img.png"> <span>Хотите научиться кататься на маунтин-байке или сноуборде?</span>
                        </span>
                        <span>
                            <img src="images/checked-img.png"><span>Хотите порхать как бабочка и жалить как пчела?</span>
                        </span>
                        <span>
                            <img src="images/checked-img.png"><span>Хотите обтекать и быть водой?</span>
                        </span>
                        <button class="btn1">
                            <i class="fas fa-search"></i>  подберите инструктора для себя
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Instruktory block -->


        <!-- Instruktory -->
        <div class="instruktory">
            <div class="row justify-content-center container2">
                <h1>Наши инструкторы</h1>
                <div class="col-lg-3 col-xl-2 col-md-4 col-sm-5">
                    <div class="desc-block">
                        <img src="images/instr1.png">
                        <div class="desc">
                            <h1>Гришин</h1>
                            <h2>Владислав</h2>
                            <div>Тренер по фрирайду</div>
                            <span>Опыт 12 лет</span>
                        </div>

                    </div>

                </div>
                <div class="col-lg-3 col-xl-2 col-md-4 col-sm-5">
                    <div class="desc-block">
                        <img src="images/instr2.png">
                        <div class="desc">
                            <h1>Понамарев</h1>
                            <h2>Егор</h2>
                            <div>ТИнструктор-саентолог</div>
                            <span>Опыт 10 лет</span>
                        </div>

                    </div>

                </div>
                <div class="col-lg-3 col-xl-2 col-md-4 col-sm-5">
                    <div class="desc-block">
                        <img src="images/instr3.png">
                        <div class="desc">
                            <h1>Титов</h1>
                            <h2>Тимур</h2>
                            <div>Гуру маунтин-байка</div>
                            <span>Опыт 23 года</span>
                        </div>

                    </div>
                </div>
                <div class="col-lg-3 col-xl-2 col-md-4 col-sm-5">
                    <div class="desc-block">
                        <img src="images/instr4.png">
                        <div class="desc">
                            <h1>Королёва</h1>
                            <h2>Надежда</h2>
                            <div>Тренер по йоге и пилатесу</div>
                            <span>Опыт 3 года</span>
                        </div>

                    </div>
                </div>
                <div class="col-lg-3 col-xl-2 col-md-4 col-sm-5">
                    <div class="desc-block">
                        <img src="images/instr5.png">
                        <div class="desc">
                            <h1>Беломестнов</h1>
                            <h2>Кирилл</h2>
                            <div>Тренер по вэйкборду</div>
                            <span>Опыт 3 года</span>
                        </div>

                    </div>
                </div>
            </div>
            <a href="{{route('coach.index')}}" class="more-btn">СМОТРЕТЬ ЕЩЁ</a>
        </div>
        <!-- /Instruktory -->


        <!-- Arenda snaryazhenia -->
        <div class="arenda-block">
            <img src="images/girl.png" alt="girl" class="girl">
            <div class="container2">
                <h1 class="arenda-h">АРЕНДА СНАРЯЖЕНИЯ</h1>
                <ul class="arenda-sp">
                    <li>
                        <div><img src="images/arenda-img-1.png"></div>
                        <span>Для катания <br>на лыжах</span>
                    </li>
                    <li>
                        <div><img src="images/arenda-img-2.png"></div>
                        <span>Для катания<br>на сноуборде</span>
                    </li>
                    <li>
                        <div><img src="images/arenda-img-3.png"></div>
                        <span>Для походов<br>и активного отдыха</span>
                    </li>
                </ul>
                <div class="txt">
                    <p>Язык образов решительно преобразует даосизм. Ощущение мира амбивалентно трансформирует закон внешнего мира. Моцзы, Сюнъцзы и другие считали, что закон внешнего мира индуцирует гедонизм, открывая новые горизонты. Априори, конфликт прост.</p>
                    <p>
                        Локаята трансформирует непредвиденный бабувизм. Аналогия дискредитирует дедуктивный метод. Единственной космической субстанцией Гумбольдт считал материю, наделенную внутренней активностью, несмотря на это сомнение создает напряженный конфликт.
                    </p>
                </div>
                <button class="btn1"><i class="fas fa-search"></i> подберите снаряжение</button>
            </div>
        </div>
        <!-- /Arenda snaryazhenia -->

        <!-- Map -->
        <div class="map-block">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15406.620512738464!2d73.27345116850145!3d54.96945422916924!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x43ab017076edcbf7%3A0x2bb3dd200acffa5f!2z0JzQtdCz0LAg0J7QvNGB0Lo!5e0!3m2!1sru!2s!4v1521989624694" width="" height="" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        <!-- /Map -->


@endsection

resources/views/pages/profile.blade.php
@extends('layouts.main')
@section('content')

<div class="container py-4">
    <h1 class="title">Личный кабинет</h1>
    <div class="card">
        <div class="card-body">

        </div>
    </div>
</div>

@endsection